/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.RegistroController;
import Models.Registro;
import Models.RegistroDao;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.NoSuchProviderException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author chuec
 */
public class SystemView extends javax.swing.JFrame {

    int xMouse, yMouse;
    Registro registro = new Registro();
    RegistroDao registroDao = new RegistroDao();

    private static String emailFrom = "fgribaudo479@gmail.com";
    private static String passwordFrom = "otipgyoezydmpzpi";
    private String emailTo;
    private String subject;
    private String content;

    private Session mSesion;
    private MimeMessage mCorreo;

    public SystemView() {
        initComponents();
        setSize(918, 454);
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("panel de registro");
        RegistroController controller = new RegistroController(registro, registroDao, this);

    }

    private void createEmail() {
        int rowCount = totalTable.getRowCount();
        int columnCount = totalTable.getColumnCount();

        StringBuilder tableData = new StringBuilder();

        for (int row = 0; row < rowCount; row++) {
            for (int col = 0; col < columnCount; col++) {
                Object cellValue = totalTable.getValueAt(row, col);
                if (cellValue == null) {
                    cellValue = ""; // Asignar una cadena vacía u otro valor predeterminado
                }
                tableData.append(cellValue.toString());
                tableData.append("\t"); // Agregar un separador (por ejemplo, una pestaña)
            }
            tableData.append("\n"); // Agregar un salto de línea entre filas
        }

        emailTo = txtDestinatario.getText().trim();
        subject = txtAsunto.getText().trim();
        content = tableData.toString();

        Properties mProperties = new Properties();
        mProperties.put("mail.smtp.host", "smtp.gmail.com");
        mProperties.put("mail.smtp.ssl.trust", "smtp.gmail.com");
        mProperties.setProperty("mail.smtp.starttls.enable", "true");
        mProperties.setProperty("mail.smtp.port", "587");
        mProperties.setProperty("mail.smtp.user", emailFrom);
        mProperties.setProperty("mail.smtp.ssl.protocols", "TLSv1.2");
        mProperties.setProperty("mail.smtp.auth", "true");

        mSesion = Session.getDefaultInstance(mProperties);

        try {
            mCorreo = new MimeMessage(mSesion);
            mCorreo.setFrom(new InternetAddress(emailFrom));
            mCorreo.setRecipient(Message.RecipientType.TO, new InternetAddress(emailTo));
            mCorreo.setSubject(subject);
            mCorreo.setText(content);

        } catch (AddressException ex) {
            Logger.getLogger(SystemView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MessagingException ex) {
            Logger.getLogger(SystemView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void sendEmail() {
        try {
            Transport mTransport = mSesion.getTransport("smtp");
            mTransport.connect(emailFrom, passwordFrom);
            mTransport.sendMessage(mCorreo, mCorreo.getRecipients(Message.RecipientType.TO));
            mTransport.close();

            JOptionPane.showMessageDialog(null, "correo enviado");
        } catch (NoSuchProviderException ex) {
            Logger.getLogger(SystemView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MessagingException ex) {
            Logger.getLogger(SystemView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_openProduct = new javax.swing.JButton();
        btn_closeProduct = new javax.swing.JButton();
        btn_registerProfuct = new javax.swing.JButton();
        btn_total = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        txt_codeProduct = new javax.swing.JTextField();
        txt_nameProduct = new javax.swing.JTextField();
        btn_register = new javax.swing.JButton();
        txt_productVencimiento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mLibre = new javax.swing.JLabel();
        txt_cantidadM = new javax.swing.JTextField();
        pickit = new javax.swing.JLabel();
        txt_cantidadP = new javax.swing.JTextField();
        btn_cantidadTotal = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txt_cantidadMercadoLibre = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_cantidadPickit = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        cantidadTabla = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        txt_searchProduct = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        txt_searchCode = new javax.swing.JTextField();
        txt_searchName = new javax.swing.JTextField();
        btn_enter = new javax.swing.JButton();
        txt_productID = new javax.swing.JTextField();
        cmb_packages = new javax.swing.JComboBox<>();
        btn_cancel = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        productDetailsTable = new javax.swing.JTable();
        txt_productDetails = new javax.swing.JTextField();
        btn_deleteTable = new javax.swing.JButton();
        btn_clearCampos = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        totalTable = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        txtDestinatario = new javax.swing.JTextField();
        txtAsunto = new javax.swing.JTextField();
        txtMensaje = new javax.swing.JTextField();
        btn_enviar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/311573235_436553155288146_1242657602518654846_n.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 130));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REGISTRO PICKIT");
        jLabel2.setToolTipText("");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        jPanel4.setBackground(new java.awt.Color(253, 83, 9));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cerrar (1).png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 25, 25));

        jPanel3.setBackground(new java.awt.Color(253, 83, 9));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(253, 83, 9));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/minimizar (1).png"))); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(834, 0, 30, 24));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 30));

        btn_openProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_openProduct.setText("Entrada");
        btn_openProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btn_openProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 100, -1));

        btn_closeProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_closeProduct.setText("Salida");
        btn_closeProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btn_closeProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 100, -1));

        btn_registerProfuct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_registerProfuct.setText("Registro");
        btn_registerProfuct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btn_registerProfuct, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 100, -1));

        btn_total.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_total.setText("Total");
        btn_total.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btn_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 130));

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel6.setBackground(new java.awt.Color(253, 83, 9));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 0, 0));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_codeProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel10.add(txt_codeProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 140, -1));

        txt_nameProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel10.add(txt_nameProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 140, -1));

        btn_register.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_register.setText("Ingresar");
        btn_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel10.add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        txt_productVencimiento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel10.add(txt_productVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 140, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel7.setText("Codigo :");
        jPanel10.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel8.setText("Nombre :");
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel10.setText("Fecha Vencimiento :");
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jPanel6.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 410, 210));

        mLibre.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        mLibre.setText("MLibre");
        jPanel6.add(mLibre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        txt_cantidadM.setEditable(false);
        txt_cantidadM.setBackground(new java.awt.Color(253, 83, 9));
        txt_cantidadM.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        txt_cantidadM.setBorder(null);
        jPanel6.add(txt_cantidadM, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 50, -1));

        pickit.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        pickit.setText("Pickit");
        jPanel6.add(pickit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        txt_cantidadP.setEditable(false);
        txt_cantidadP.setBackground(new java.awt.Color(253, 83, 9));
        txt_cantidadP.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        txt_cantidadP.setBorder(null);
        jPanel6.add(txt_cantidadP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 50, -1));

        btn_cantidadTotal.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btn_cantidadTotal.setText("ingresar cantidades");
        btn_cantidadTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.add(btn_cantidadTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 170, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel16.setText("Cantidad MLibre");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        txt_cantidadMercadoLibre.setEditable(false);
        txt_cantidadMercadoLibre.setBackground(new java.awt.Color(253, 83, 9));
        txt_cantidadMercadoLibre.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        txt_cantidadMercadoLibre.setBorder(null);
        jPanel6.add(txt_cantidadMercadoLibre, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 50, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel17.setText("CantidadPickit");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, -1, -1));

        txt_cantidadPickit.setEditable(false);
        txt_cantidadPickit.setBackground(new java.awt.Color(253, 83, 9));
        txt_cantidadPickit.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        txt_cantidadPickit.setBorder(null);
        jPanel6.add(txt_cantidadPickit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 50, -1));

        cantidadTabla.setBackground(new java.awt.Color(255, 0, 0));
        cantidadTabla.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        cantidadTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MERCADOLIBRE", "CANTIDAD", "PICKIT", "CANTIDAD", "FECHA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(cantidadTabla);

        jPanel6.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 460, 230));

        jTabbedPane1.addTab("Registro", jPanel6);

        jPanel7.setBackground(new java.awt.Color(253, 83, 9));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productTable.setBackground(new java.awt.Color(255, 0, 0));
        productTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE", "INGRESO", "VENCIMIENTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productTable);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 60, 650, 220));

        txt_searchProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel7.add(txt_searchProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 180, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel9.setText("Buscar :");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jTabbedPane1.addTab("Entrada", jPanel7);

        jPanel8.setBackground(new java.awt.Color(253, 83, 9));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 0, 0));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_searchCode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel9.add(txt_searchCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 150, -1));

        txt_searchName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel9.add(txt_searchName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 150, -1));

        btn_enter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_enter.setText("Enter");
        btn_enter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel9.add(btn_enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        txt_productID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel9.add(txt_productID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 80, -1));

        cmb_packages.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_packages.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entregado", "Vencido", " " }));
        cmb_packages.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel9.add(cmb_packages, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 150, -1));

        btn_cancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cancel.setText("Cancelar");
        btn_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel9.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel11.setText("ID :");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel3.setText("Codigo :");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel4.setText("Nombre :");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, 270));

        productDetailsTable.setBackground(new java.awt.Color(255, 0, 0));
        productDetailsTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        productDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "CODIGO", "NOMBRE", "ENT/VEN", "FECHA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(productDetailsTable);
        if (productDetailsTable.getColumnModel().getColumnCount() > 0) {
            productDetailsTable.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 80, 530, 200));

        txt_productDetails.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel8.add(txt_productDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 160, -1));

        btn_deleteTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_deleteTable.setText("Limpiar Tabla");
        btn_deleteTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.add(btn_deleteTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, -1, -1));

        btn_clearCampos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_clearCampos.setText("Limpiar Campos");
        btn_clearCampos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.add(btn_clearCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel12.setText("Buscar :");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        jTabbedPane1.addTab("Salida", jPanel8);

        jPanel11.setBackground(new java.awt.Color(253, 83, 9));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalTable.setBackground(new java.awt.Color(255, 0, 0));
        totalTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE", "ENTRADA", "SALIDA", "ENT/VEN", "VENCIMIENTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(totalTable);

        jPanel11.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 20, 820, 250));

        jTabbedPane1.addTab("Total", jPanel11);

        jPanel12.setBackground(new java.awt.Color(253, 83, 9));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDestinatario.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jPanel12.add(txtDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 150, -1));

        txtAsunto.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jPanel12.add(txtAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 150, -1));

        txtMensaje.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jPanel12.add(txtMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 170, -1));

        btn_enviar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btn_enviar.setText("Enviar");
        btn_enviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });
        jPanel12.add(btn_enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel13.setText("Correo:");
        jPanel12.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel14.setText("Asunto:");
        jPanel12.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel15.setText("Mensaje:");
        jPanel12.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, -1));

        jTabbedPane1.addTab("Enviar", jPanel12);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 131, 920, 324));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 918, 454));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
    }//GEN-LAST:event_jLabel5MouseExited

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        createEmail();
        sendEmail();
        registroDao.deleteRowsExceptNullEgreso();
    }//GEN-LAST:event_btn_enviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_cancel;
    public javax.swing.JButton btn_cantidadTotal;
    public javax.swing.JButton btn_clearCampos;
    public javax.swing.JButton btn_closeProduct;
    public javax.swing.JButton btn_deleteTable;
    public javax.swing.JButton btn_enter;
    private javax.swing.JButton btn_enviar;
    public javax.swing.JButton btn_openProduct;
    public javax.swing.JButton btn_register;
    public javax.swing.JButton btn_registerProfuct;
    public javax.swing.JButton btn_total;
    public javax.swing.JTable cantidadTabla;
    public javax.swing.JComboBox<String> cmb_packages;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public javax.swing.JPanel jPanel7;
    public javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JLabel mLibre;
    public javax.swing.JLabel pickit;
    public javax.swing.JTable productDetailsTable;
    public javax.swing.JTable productTable;
    public javax.swing.JTable totalTable;
    private javax.swing.JTextField txtAsunto;
    private javax.swing.JTextField txtDestinatario;
    private javax.swing.JTextField txtMensaje;
    public javax.swing.JTextField txt_cantidadM;
    public javax.swing.JTextField txt_cantidadMercadoLibre;
    public javax.swing.JTextField txt_cantidadP;
    public javax.swing.JTextField txt_cantidadPickit;
    public javax.swing.JTextField txt_codeProduct;
    public javax.swing.JTextField txt_nameProduct;
    public javax.swing.JTextField txt_productDetails;
    public javax.swing.JTextField txt_productID;
    public javax.swing.JTextField txt_productVencimiento;
    public javax.swing.JTextField txt_searchCode;
    public javax.swing.JTextField txt_searchName;
    public javax.swing.JTextField txt_searchProduct;
    // End of variables declaration//GEN-END:variables
}
